### ISSUE TITLE
Next steps on the road to version 0.10.x

### ISSUE THREAD

**Issue by Shinigami92** [htmlhint/HTMLHint#259]
## This is not a feature or bug issue

I'd like to suggest / list some TODOs and changes before we can provide a new tag

I think the next version should be 0.10.0 instead of 1.0.0 because we do not want to make any changes for a release but for a new clean, automated, and improved project.

-----------

### Pull Request

-   [x] #179 Update JShint and CSSlint deps
-   [x] #214 Is it dead? (can be closed 🎉)
-   [x] #251 Update dependencies to enable Greenkeeper 🌴 
-   [ ] #255 added prettier with husky
-   [x] #246 update packages
-   [x] #257 Add sematic-release to package.json

### CleanUp and Improvements

-   pom.xml
    -   [package.json#people-fields-author-contributors](https://docs.npmjs.com/files/package.json#people-fields-author-contributors)
        -   [x] Change "author" to @thedaviddias 
        -   [x] Move @yaniswang to "contributors"
        -   [x] Add @ArmorDarks to "contributors"
    - dependencies
        -   [x] Review versions of dependencies and update them to the latest compatible versions
            -   [x] #246 update packages
            -   [x] #179 Update JShint and CSSlint deps
        -   [x] Use [npm-audit](https://docs.npmjs.com/cli/audit) to identify vulnerabilities
-   Build automation
    -   [x] #251 Update dependencies to enable Greenkeeper 🌴 
    -   [ ] #255 added prettier with husky
    -   [x] #256 Add sematic-release to package.json
    -   [ ] #258 Add commitizen package

-----------

After making all these changes, we can set the version to 0.10.0, tag it and maybe release it.

Then we should focus on implementing and bringing together the current open pull requests that are waiting the last 1-3 years ^^
And from then on, we can increment the version from 0.10.0 to 0.10.1+ or 0.11.x+

**Comment by Shinigami92** [comment]
We may close this issue when https://github.com/htmlhint/HTMLHint/pull/388 is merged
